import re


EXACT_LABELS = {
    "court": "Суд",
    "court_name": "Наименование суда",
    "court_name_text": "Наименование суда",
    "court_address": "Адрес суда",
    "in_court_name": "В какой суд подается документ",

    "plaintiff": "Истец",
    "plaintiff_name": "ФИО / наименование истца",
    "plaintiff_fio": "ФИО истца",
    "plaintiff_address": "Адрес истца",
    "plaintiff_passport": "Паспортные данные истца",
    "plaintiff_registration_address": "Адрес регистрации истца",
    "plaintiff_details": "Данные истца",
    "plaintiff_role": "Роль истца",
    "plaintiff_obligation": "Обязанность истца",
    "plaintiff_representative": "Представитель истца",

    "defendant": "Ответчик",
    "defendant_name": "ФИО / наименование ответчика",
    "defendant_address": "Адрес ответчика",
    "defendant_passport": "Паспортные данные ответчика",
    "defendant_registration_address": "Адрес регистрации ответчика",
    "defendant_details": "Данные ответчика",
    "defendant_role": "Роль ответчика",
    "defendant_obligation": "Обязанность ответчика",
    "defendant_belief": "Позиция ответчика",

    "applicant": "Заявитель",
    "applicant_passport": "Паспортные данные заявителя",
    "applicant_registration_address": "Адрес регистрации заявителя",
    "applicant_role": "Роль заявителя",

    "signature": "Подпись",
    "signatory_name": "ФИО подписанта",
    "document_date": "Дата документа",
    "document_city": "Город составления документа",

    "claim_price": "Цена иска",
    "state_duty": "Госпошлина",
    "state_duty_amount": "Размер госпошлины",
    "claim_subject": "Предмет требований",
    "claim_demands": "Требования",
    "claim_requests": "Просительная часть",
    "claim_facts": "Фактические обстоятельства",
    "claim_details": "Обстоятельства требований",
    "claim_attachments": "Приложения к иску",

    "debt_amount": "Сумма задолженности",
    "amount_of_debt": "Сумма задолженности",
    "total_debt_amount": "Общая сумма задолженности",
    "penalty_amount": "Сумма неустойки",
    "interest_amount": "Сумма процентов",
    "moral_damage_amount": "Размер морального вреда",
    "moral_compensation_amount": "Размер компенсации морального вреда",

    "contract_type": "Вид договора",
    "contract_number": "Номер договора",
    "contract_num": "Номер договора",
    "contract_date": "Дата договора",
    "contract_price": "Цена договора",
    "contract_subject": "Предмет договора",
    "contract_details": "Условия договора",
    "contract_obligations": "Обязательства по договору",

    "marriage_date": "Дата заключения брака",
    "divorce_reasons": "Причины расторжения брака",
    "children_name": "ФИО детей",
    "children_birth_year": "Год рождения детей",
    "children_date_of_birth": "Дата рождения детей",
    "upbringing_conditions": "Условия воспитания детей",

    "attachments": "Приложения",
    "attachments_list": "Список приложений",
    "evidence": "Доказательства",
    "evidence_list": "Список доказательств",
    "legal_grounds": "Правовые основания",
    "additional_request": "Дополнительное требование",

    "repayment_deadline": "Срок возврата / оплаты",

    "married_to": "Дата заключения брака",
    "married_until": "Дата прекращения семейных отношений",
    "mattied_until": "Дата прекращения семейных отношений",
    "date_dissolved_marriage": "Дата расторжения брака",
    "who_dissolved_the_marriage": "Кем расторгнут брак",
    "description_of_property": "Описание совместного имущества",

    "plaintiff_text": "ФИО истца в нужном падеже",
    "plaintiff_text_third": "ФИО истца в нужном падеже",
    "defendant_text": "ФИО ответчика в нужном падеже",
    "defendant_text_third": "ФИО ответчика в нужном падеже",
    "defendant_text_fourth": "ФИО ответчика в нужном падеже",
    "defendant_text_with": "ФИО ответчика в творительном падеже",
    "defendant_rod": "ФИО ответчика в родительном падеже",
    "defendant_tvor": "ФИО ответчика в творительном падеже",
    "children_name_rod": "ФИО детей в родительном падеже",
    "children_name_tvor": "ФИО детей в творительном падеже",
    "children_name_by": "ФИО детей в дательном падеже",
    "children_name_text": "ФИО детей в нужном падеже",
    "children_name_text_two": "ФИО второго ребенка в нужном падеже",
    "children_name_text_third": "ФИО третьего ребенка в нужном падеже",
    "children_name_third": "ФИО третьего ребенка",
    "children_year_of_birth": "Год рождения детей",

    "passport_plaintiff": "Паспортные данные истца",
    "passport_defendant": "Паспортные данные ответчика",
    "plantiff": "Истец",
    "plantiff_fio": "ФИО истца",
    "defails": "Дополнительные данные",

    "full_name_of_the_buyer": "ФИО покупателя",
    "full_name_of_the_seller": "ФИО продавца",
    "passport_series_of_the_buyer": "Серия паспорта покупателя",
    "passport_number_of_the_buyer": "Номер паспорта покупателя",
    "passport_series_of_the_seller": "Серия паспорта продавца",
    "passport_number_of_the_seller": "Номер паспорта продавца",
    "date_of_issue_of_the_passport_of_the_buyer": "Дата выдачи паспорта покупателя",
    "date_of_issue_of_the_passport_of_the_seller": "Дата выдачи паспорта продавца",
    "who_issued_the_passport_of_the_buyer": "Кем выдан паспорт покупателя",
    "who_issued_the_passport_of_the_seller": "Кем выдан паспорт продавца",
    "registration_address_of_the_buyer": "Адрес регистрации покупателя",
    "registration_address_of_the_seller": "Адрес регистрации продавца",
    "citizenship_of_the_buyer": "Гражданство покупателя",
    "citizenship_of_the_seller": "Гражданство продавца",

    "party_1": "Первая сторона",
    "party_2": "Вторая сторона",
    "party_one_name": "ФИО / наименование первой стороны",
    "party_two_name": "ФИО / наименование второй стороны",
    "party_one_representative": "Представитель первой стороны",
    "party_two_representative": "Представитель второй стороны",

    "claim_one_amount": "Сумма первого требования",
    "claim_two_amount": "Сумма второго требования",
    "claim_three_amount": "Сумма третьего требования",
    "claim_one_nature": "Суть первого требования",
    "claim_two_nature": "Суть второго требования",
    "claim_three_nature": "Суть третьего требования",

    "date_of_the_court_decision": "Дата судебного решения",
    "date_of_leaving_family": "Дата прекращения совместного проживания",
    "date_of_leaving_the_family": "Дата прекращения совместного проживания",
    "leave_family_date": "Дата прекращения совместного проживания",

    "amount_of_alimony_payment": "Размер алиментного платежа",
    "new_amount_of_alimony_payment": "Новый размер алиментного платежа",
    "method_of_collection_before": "Прежний способ взыскания алиментов",
    "new_method_of_collection": "Новый способ взыскания алиментов",
    "order_of_communication": "Порядок общения с ребенком",
    "confirmation_of_paternity": "Подтверждение отцовства",
    "description_and_reasons_for_deprivation_of_parental_rights": "Обстоятельства и основания лишения родительских прав",

    "average_monthly_income_of_the_plaintiff": "Среднемесячный доход истца",
    "part_average_monthly_income_of_the_plaintiff": "Доля среднемесячного дохода истца",
    "share_of_the_plaintiff_average_monthly_income": "Доля среднемесячного дохода истца",
    "share_of_the_plaintiffs_average_monthly_income": "Доля среднемесячного дохода истца",

    "the_reason_why_there_were_no_payments": "Причина отсутствия платежей",
    "the_reason_why_the_plaintiff_could_not_pay_alimony": "Причина невозможности уплаты алиментов истцом",
    "where_the_defendant_works_now_and_how_much_does_he_earn": "Где сейчас работает ответчик и сколько зарабатывает",
    "where_the_defendant_worked_and_how_much_he_earned_at_the_time_of_the_court_decis": "Где работал ответчик и сколько зарабатывал на дату судебного решения",
    "information_about_the_defendants_income": "Сведения о доходе ответчика",
    "information_about_the_defendants_position": "Сведения о месте работы / должности ответчика",
    "the_relationship_of_the_plaintiff_to_the_defendant": "Кем истец приходится ответчику",

    "of_commencement_of_child": "Дата начала содержания ребенка",
    "of_issuance_of_the": "Дата выдачи документа",
    "of_leaving": "Дата ухода из семьи",
    "of_leaving_the": "Дата ухода из семьи",
}

EXACT_LABELS.update({
    "site_address": "Адрес участка",
    "what_is_there_not_enough_money_for": "На что не хватает денежных средств",
    "who_is_the_plaintiff_to_a_family_member": "Кем истец приходится члену семьи",
    "what_the_defendant_must_pay": "Что должен выплатить ответчик",
    "defendant_vin": "VIN ответчика",
    "age_for_receiving_a_preferential_pension": "Возраст для назначения льготной пенсии",
    "by_whom_and_what_decision_was_made": "Кем и каким решением принято",
    "topic_of_statement": "Тема заявления",
    "what_type_of_work_does_the_plaintiffs_profession_belong_to": "К какому виду работ относится профессия истца",
    "what_was_the_plaintiff_doing": "Чем занимался истец",
    "inability_description": "Описание невозможности",
    "incapacitated_person_name": "ФИО недееспособного лица",
    "incapacitated_pronoun": "Местоимение для недееспособного лица",
    "purpose": "Цель обращения",
    "evidence_of_sham_transaction": "Доказательства мнимости сделки",
    "legal_action_description": "Описание юридически значимого действия",
    "sham_contract_date": "Дата мнимого договора",
    "sham_contract_type": "Вид мнимого договора",
    "sham_price": "Цена мнимой сделки",
    "suspicious_action_description": "Описание подозрительных действий",
    "third_party_name": "ФИО / наименование третьего лица",
    "give_to_defendant": "Передать ответчику",
    "give_to_plaintiff": "Передать истцу",
    "proportions_paid": "Оплаченные доли",
    "defendant_regional_office": "Территориальное подразделение ответчика",
    "other_owner_name": "ФИО / наименование другого собственника",
    "purpose_of_loan": "Цель получения займа",
    "where_target_loan_now": "На что сейчас направлен заем",
    "incapacity_evidence_description": "Описание доказательств недееспособности",
    "new_wording_of_the_dismissal": "Новая формулировка причины увольнения",
    "material_to_provide": "Материалы, которые нужно предоставить",
    "documents_to_inspect": "Документы для ознакомления",
    "waiting_period": "Период ожидания",
    "does_not_allow_communication_details": "Обстоятельства препятствования общению",
    "mother_or_father": "Мать или отец",
    "son_or_daughter": "Сын или дочь",
    "compelling_circumstances": "Уважительные обстоятельства",
    "debt_stop_date": "Дата прекращения задолженности",
    "children_name_text_one_prekratit_uderzhivat_s_menya_alimenty_na_soderzhanie_chil": "ФИО ребенка в формулировке о прекращении удержания алиментов",
    "details_statement_of_defendant": "Содержание заявления ответчика",
    "amount_of_monthly_payments": "Размер ежемесячных платежей",
    "court_name_tvor": "Наименование суда в творительном падеже",
    "text_with": "Текст с указанием лица",
    "what_type_of_profession_does_the_plaintiff_have": "Какая профессия у истца",
    "what_was_not_known_at_the_time_the_judgment_was_rendered": "Что не было известно на момент вынесения решения",
    "who_was_the_plaintiff_at_the_time_of_the_judgment": "Кем был истец на момент вынесения решения",
    "possession_background": "Основания владения",
    "possession_details": "Обстоятельства владения",
    "possession_start_date": "Дата начала владения",
    "dependant_details": "Сведения об иждивенце",
    "dependent_details": "Сведения об иждивенце",
    "reason_for_host_act": "Причина составления акта",
    "inheritance_issue": "Наследственный вопрос",
    "relationship_details": "Сведения о родственных отношениях",
    "child_abandonment_details": "Обстоятельства оставления ребенка",
    "kinship_requested": "Родственная связь, которую нужно установить",
    "born_person_details": "Сведения о рожденном лице",
    "in_power": "В силу полномочий",
    "name_testimony": "ФИО свидетеля",
    "passport_data": "Паспортные данные",
    "problem": "Суть проблемы",
    "defendant_responsibilities": "Обязанности ответчика",
    "plaintiff_responsibilities": "Обязанности истца",
    "defects_description": "Описание недостатков",
    "actual_frequency": "Фактическая периодичность",
    "scheduled_frequency": "Установленная периодичность",
    "relationship_description": "Описание взаимоотношений сторон",
    "repayment_date": "Дата возврата",
    "name_or": "ФИО / наименование организации",
    "silence_period": "Период отсутствия ответа",
    "amendment_claims": "Уточненные требования",
    "amendment_reasons": "Причины уточнения требований",
})

TOKEN_LABELS = {
    "accident": "ДТП",
    "accommodation": "проживание",
    "account": "счет",
    "act": "акт",
    "actual": "фактический",
    "additional": "дополнительный",
    "address": "адрес",
    "agreement": "соглашение",
    "airline": "авиакомпания",
    "alimony": "алименты",
    "amount": "сумма",
    "apartment": "квартира",
    "applicant": "заявитель",
    "application": "заявление",
    "arrears": "задолженность",
    "arrival": "прибытие",
    "article": "статья",
    "attachment": "приложение",
    "attachments": "приложения",
    "bank": "банк",
    "birth": "рождение",
    "borrower": "заемщик",
    "buyer": "покупатель",
    "cadastral": "кадастровый",
    "case": "дело",
    "child": "ребенок",
    "children": "дети",
    "citizenship": "гражданство",
    "city": "город",
    "claim": "требование",
    "claims": "требования",
    "client": "клиент",
    "company": "организация",
    "compensation": "компенсация",
    "complaint": "жалоба",
    "contract": "договор",
    "contractor": "исполнитель",
    "court": "суд",
    "creditor": "кредитор",
    "current": "текущий",
    "damage": "ущерб",
    "date": "дата",
    "debt": "задолженность",
    "debtor": "должник",
    "defendant": "ответчик",
    "delay": "просрочка",
    "delivery": "поставка",
    "demand": "требование",
    "departure": "отправление",
    "details": "данные",
    "divorce": "расторжение брака",
    "document": "документ",
    "employer": "работодатель",
    "employment": "работа",
    "evidence": "доказательства",
    "event": "событие",
    "expertise": "экспертиза",
    "facts": "обстоятельства",
    "family": "семья",
    "fee": "пошлина",
    "fio": "ФИО",
    "grounds": "основания",
    "heir": "наследник",
    "income": "доход",
    "incident": "происшествие",
    "info": "сведения",
    "interest": "проценты",
    "issue": "вопрос",
    "law": "закон",
    "legal": "правовой",
    "lender": "займодавец",
    "lessee": "арендатор",
    "lessor": "арендодатель",
    "list": "список",
    "loan": "заем",
    "location": "место",
    "loss": "убыток",
    "marriage": "брак",
    "moral": "моральный",
    "name": "наименование / ФИО",
    "number": "номер",
    "obligation": "обязанность",
    "obligations": "обязанности",
    "offender": "нарушитель",
    "order": "приказ / порядок",
    "organization": "организация",
    "passport": "паспортные данные",
    "payment": "платеж",
    "penalty": "неустойка",
    "period": "период",
    "person": "лицо",
    "plaintiff": "истец",
    "price": "цена",
    "property": "имущество",
    "recipient": "получатель / адресат",
    "registration": "регистрация",
    "representative": "представитель",
    "request": "требование / просьба",
    "requisites": "реквизиты",
    "residence": "место жительства",
    "role": "роль",
    "seller": "продавец",
    "sender": "отправитель",
    "service": "услуга",
    "signature": "подпись",
    "subject": "предмет",
    "sum": "сумма",
    "tenant": "наниматель / арендатор",
    "text": "текст",
    "total": "общий",
    "vehicle": "транспортное средство",
    "violation": "нарушение",
    "witness": "свидетель",
    "work": "работа",
    "year": "год",

    "full": "полное",
    "short": "краткое",
    "phone": "телефон",
    "contact": "контактные",
    "description": "описание",
    "and": "и",
    "new": "новые",
    "initial": "первоначальный",
    "evaluation": "оценка",
    "car": "автомобиль",
    "model": "модель",
    "damaged": "поврежденное",
    "cause": "причина",
    "signatures": "подписи",
    "flight": "рейс",
    "gk": "ГК РФ",
    "day": "день",
    "item": "пункт",
    "title": "наименование",
    "specific": "конкретные",
    "demands": "требования",
    "telefon": "телефон",
    "adres": "адрес",
    "registracii": "регистрации",
    "product": "товар",
    "purchase": "покупка",
    "shop": "магазин",
    "insurance": "страхование",
    "object": "объект",
    "requested": "запрошенная",
    "apartment": "квартира",
    "num": "номер",
    "floor": "этаж",
    "house": "дом",
    "street": "улица",
    "club": "клуб",
    "owner": "собственник",
    "refund": "возврат",
    "sub": "тип",
    "type": "тип",
    "time": "время",
    "passed": "прошло",
    "responsible": "ответственное",
    "builder": "застройщик",
    "since": "с момента",
    "completion": "завершение",
    "provider": "поставщик услуг",
    "due": "срок",
    "principal": "основной долг",
    "requirements": "требования",
    "receipt": "получение",
    "dispute": "спорные",
    "infringer": "нарушитель",
    "injured": "пострадавшая",
    "party": "сторона",
    "rent": "арендная плата",
    "acc": "в винительном падеже",
    "gen": "в родительном падеже",
    "return": "возврат",
    "reason": "причина",
    "smartphone": "смартфон",
    "error": "ошибка",
    "furniture": "мебель",
    "warranty": "гарантийный",
    "works": "работы",
    "start": "начало",
    "end": "окончание",
    "death": "смерть",
    "deceased": "умерший",
    "declension": "в нужном падеже",
    "enriched": "обогатившаяся",
    "enrichment": "неосновательное обогащение",
    "impoverished": "потерпевшая",
    "operator": "оператор",
    "salon": "салон",
    "status": "статус",
    "last": "последний",
    "medical": "медицинские",
    "expenses": "расходы",
    "damages": "вред",
    "deadline": "срок",
    "job": "должность",
    "pay": "выплата",
    "salary": "заработная плата",
    "cancel": "отмена",
    "tour": "туроператор",
    "vacation": "поездка / отдых",
    "depositor": "поклажедатель",
    "keeper": "хранитель",
    "storage": "хранение",
    "conditions": "условия",
    "term": "срок",
    "ruling": "определение суда",
    "month": "месяц",
    "of": "",
    "the": "",
    "for": "для",
    "to": "для",
    "notification": "уведомление",
    "changes": "изменения",
    "submitting": "подача",
    "documents": "документы",
    "rights": "права",
    "authority": "орган",
    "submitted": "поданные",
    "method": "способ",
    "sending": "направление",
    "days": "дни",
    "response": "ответ",
    "transfer": "перечисление",
    "money": "деньги",
    "houses": "дома",
    "floors": "этажи",
    "doc": "документ",
    "rooms": "комнаты",
    "square": "площадь",
    "basis": "основание",
    "ownership": "право собственности",
    "residential": "жилой",
    "premises": "помещение",
    "landlord": "арендодатель",
    "who": "кто",
    "lives": "проживает",
    "is": "",
    "registered": "зарегистрирован",
    "in": "в",
    "flat": "квартира",
    "pays": "оплачивает",
    "expenses": "расходы",
    "first": "первое",
    "second": "второе",
    "argument": "обоснование",
    "explanation": "пояснение",
    "id": "реквизиты / идентификатор",
    "original": "первоначальный",
    "situation": "ситуация",
    "amended": "уточненные",
    "change": "изменение",
    "further": "дополнительные",
    "defense": "возражения",
    "arguments": "доводы",
    "director": "директор",
    "dismissal": "увольнение",
    "context": "обстоятельства",
    "position": "должность / позиция",
    "reinstatement": "восстановление",
    "workplace": "место работы",
    "calculated": "рассчитанная",
    "monthly": "ежемесячная",
    "paid": "уплаченная",
    "recalculation": "перерасчет",
    "scheduled": "установленная",
    "defect": "недостаток",
    "clain": "требование",
    "harm": "вред",
    "patry": "сторона",
    "performance": "оказание услуги / выполнение работ",
    "cost": "стоимость",
    "bill": "счет",
    "establishment": "заведение / организация",
    "expected": "ожидаемая",
    "staff": "персонал",
    "reaction": "реакция",
    "unordered": "не заказанные",
    "items": "позиции",
    "services": "услуги",
    "discovery": "обнаружение",
    "extra": "дополнительная",
    "charge": "плата",
    "charges": "начисления",
    "package": "пакет услуг",
    "contents": "содержание",
    "refusal": "отказ",
    "store": "магазин",
    "prepayment": "предоплата",
    "nature": "характер",
    "target": "адресат / цель",
    "guilty": "виновная",
    "osago": "ОСАГО",
    "participant": "участник",
    "protocol": "протокол",
    "occurrence": "событие",
    "circumstances": "обстоятельства",
    "value": "стоимость",
    "market": "рыночный",
    "analysis": "анализ",
    "equipment": "оборудование",
    "failure": "поломка",
    "repair": "ремонт",
    "parts": "детали",
    "attended": "посещенные",
    "sessions": "занятия",
    "membership": "абонемент",
    "alternative": "альтернативная",
    "clinic": "клиника",
    "restoration": "восстановление",
    "behavior": "поведение",
    "travel": "поездка",
    "destination": "направление",
    "losses": "убытки",
    "after": "после",
    "from": "с",
    "part": "часть",
    "plot": "участок",
    "proof": "доказательство",
    "recovery": "взыскание",
    "pension": "пенсия",
    "not": "не",
    "enough": "достаточно",
    "at": "на",
    "present": "настоящее",
    "commencement": "начало",
    "care": "содержание / уход",
    "members": "члены",
    "member": "член",
    "requirement": "требование",
    "reasons": "причины",
    "org": "организация",
    "no": "не",
    "place": "место",
    "bonus": "премия",
    "correct": "корректные",
    "transaction": "сделка",
    "breaching": "нарушившая",
    "rod": "в родительном падеже",
    "non": "не",
    "owed": "задолженность",
    "transcript": "расшифровка",
    "terms": "условия",
    "co": "совместно",
    "habitant": "проживающее лицо",
    "participation": "участие",
    "share": "доля",
    "cancellation": "отмена",
    "clause": "пункт",
    "schedule": "график",
    "secondary": "дополнительный",
    "liability": "ответственность",
    "injury": "повреждение / вред",
    "lost": "упущенная",
    "profit": "выгода",
    "desired": "желаемая",
    "portion": "часть",
    "by": "со стороны",
    "episode": "эпизод",
    "plaintiffs": "истца",
    "where": "где",
    "he": "он",
    "asks": "просит",
    "duties": "обязанности",
    "must": "должен",
    "classification": "классификация",
    "vin": "VIN",
    "age": "возраст",
    "receiving": "получение",
    "preferential": "льготная",
    "by": "кем",
    "whom": "кем",
    "decision": "решение",
    "was": "было",
    "made": "принято",
    "access": "обращение",
    "years": "лет",
    "until": "до",
    "appeal": "обращение",
    "topic": "тема",
    "does": "",
    "profession": "профессия",
    "belong": "относится",
    "doing": "занимался",
    "security": "охрана",
    "matter": "спора",
    "relation": "отношение",
    "diagnosis": "диагноз",
    "timing": "сроки",
}

def get_field_label(variable: str) -> str:
    key = normalize_key(variable)

    if key in EXACT_LABELS:
        return EXACT_LABELS[key]

    words = [word for word in key.split("_") if word]

    if not words:
        return "Поле документа"

    translated = []

    for word in words:
        value = TOKEN_LABELS.get(word)

        if value is None:
            continue

        if value:
            translated.append(value)

    label = " ".join(translated)
    label = re.sub(r"\s+", " ", label).strip()

    if not label:
        return "Дополнительное поле документа"

    return label[:1].upper() + label[1:]


def normalize_key(value: str) -> str:
    value = str(value or "")
    value = re.sub(r"<[^>]+>", " ", value)
    value = re.sub(r"&[a-zA-Z]+;", " ", value)
    value = re.sub(r"\{[{%].*?[%}]\}", " ", value)
    value = value.replace("-", "_")
    value = value.replace(" ", "_")
    value = re.sub(r"[^a-zA-Z0-9а-яА-ЯёЁ_]+", "_", value)
    value = re.sub(r"_+", "_", value)
    return value.strip("_").lower()